### ISSUE TITLE
AWARE! SCAM!

### ISSUE THREAD

**Issue by serokos** [aDarkDev/NotPixel#58]
Dont use this script, the dev is logging your hash id and stealing acc after!

**Comment by aDarkDev** [comment]
XD tell me how ? and what is benefits of stealing api hash and id. show me my code that i stealing

**Comment by serokos** [comment]
Why is ur script asks for number and acc access then? cant it work just through hash api and id?

**Comment by aDarkDev** [comment]
go learn more man and see what is telethon

**Comment by serokos** [comment]
telethon? bro us just stole my acc 2 min ago and explaining it with "telethon"?

**Comment by aDarkDev** [comment]
what happened to ur acc?

**Comment by serokos** [comment]
when i was trying to set up your script at phone asking step someone logged into my acc using hash api and kicked me out from the acc

**Comment by aDarkDev** [comment]
### Never talk about something until you know it.

* Your account has been reset by Telegram itself because it is virtual and not real. Telegram resets suspicious virtual accounts and logs out all sessions of that account. 

* Second point: Telethon is a robot library for Telegram that takes the number and code from you. It has functions for everything in Telegram, which in my code is only used to get your account information from notpixel If I stole an account, it would be visible in the code because the code is completely open source.

**Comment by boostrapz** [comment]
> when i was trying to set up your script at phone asking step someone logged into my acc using hash api and kicked me out from the acc

bruh, I'm using this soft with 11 accounts and they're all good lol
